export const YOUTUBE_EPISODES = [
  {
    id: "1",
    status: "published",
    title: "New Beginnings💯",
    description: "",
    episode_number: 1,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VVEHX1UZkVNA/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/VEHX1UZkVNA",
  },
  {
    id: "2",
    status: "published",
    title: "They not built the same",
    description: "",
    episode_number: 2,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VyLnF8Xfw5D4/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/yLnF8Xfw5D4",
  },
  {
    id: "3",
    status: "published",
    title: "Withstanding the test of time",
    description: "",
    episode_number: 3,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VCLxWpXNNIa8/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/CLxWpXNNIa8",
  },
  {
    id: "4",
    status: "published",
    title: "Showstopping TV",
    description: "",
    episode_number: 4,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/Vxt0aid3SYg4/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/xt0aid3SYg4",
  },
  {
    id: "5",
    status: "published",
    title: "Fight or flight",
    description: "",
    episode_number: 5,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/V1yOvA3_rsEo/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/1yOvA3_rsEo",
  },
  {
    id: "6",
    status: "published",
    title: "Fireworks and Food",
    description: "",
    episode_number: 6,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VkkJVuQrnzu4/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/kkJVuQrnzu4",
  },
  {
    id: "7",
    status: "published",
    title: "Times have changed",
    description: "",
    episode_number: 7,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/Von58mzGMtvg/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/on58mzGMtvg",
  },
  {
    id: "8",
    status: "published",
    title: "Movies and Football",
    description: "",
    episode_number: 8,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VNFQXw9YXZJE/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/NFQXw9YXZJE",
  },
  {
    id: "9",
    status: "published",
    title: "Finish the lyrics🎵🎵",
    description: "",
    episode_number: 9,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/Vc5GgrGEj_zo/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/c5GgrGEj_zo",
  },
  {
    id: "0",
    status: "published",
    title: "Living By The Code",
    description: "",
    episode_number: 10,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/V7NiPKS4JzEU/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/7NiPKS4JzEU",
  },
  {
    id: "11",
    status: "published",
    title: "Lovers and Friends?",
    description: "",
    episode_number: 11,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VH4YSD0JhqFw/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/H4YSD0JhqFw",
  },
  {
    id: "12",
    status: "published",
    title: "Cursed!",
    description: "",
    episode_number: 12,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VupU4t3iN8Ls/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/upU4t3iN8Ls",
  },
  {
    id: "13",
    status: "published",
    title: "Going Back in Style",
    description: "",
    episode_number: 13,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VeO5sW7Bz1oU/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/eO5sW7Bz1oU",
  },
  {
    id: "14",
    status: "published",
    title: "To Use or Not To Use🙅",
    description: "",
    episode_number: 14,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VlnqWsvRHCp4/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/lnqWsvRHCp4",
  },
  {
    id: "15",
    status: "published",
    title: "That's Some Stereotypical....",
    description: "",
    episode_number: 15,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VNNQkWcYBpsQ/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/NNQkWcYBpsQ",
  },
  {
    id: "16",
    status: "published",
    title: "Auto what?",
    description: "",
    episode_number: 16,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/Vkzh6AHoPaBQ/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/kzh6AHoPaBQ",
  },
  {
    id: "17",
    status: "published",
    title: "Wayne's World🌏",
    description: "",
    episode_number: 17,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VaGjJGqZ4_F8/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/aGjJGqZ4_F8",
  },
  {
    id: "18",
    status: "published",
    title: "Know Your Role.....",
    description: "",
    episode_number: 18,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VmCG7evHvGk8/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/mCG7evHvGk8",
  },
  {
    id: "19",
    status: "published",
    title: "50 years of Hip-Hop🎤",
    description: "",
    episode_number: 19,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/V5q182hF7qS0/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/5q182hF7qS0",
  },
  {
    id: "20",
    status: "published",
    title: "50 Years Of Hip Hop Pt. 2",
    description: "",
    episode_number: 20,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/V66MsKese__8/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/66MsKese__8",
  },
  {
    id: "21",
    status: "published",
    title: "Double Standards",
    description: "",
    episode_number: 21,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VqtKmepxeMS8/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/qtKmepxeMS8",
  },
  {
    id: "22",
    status: "published",
    title: "Ready For Some Football!!",
    description: "",
    episode_number: 22,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/V_6SU3hMRUuE/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/_6SU3hMRUuE",
  },
  {
    id: "23",
    status: "published",
    title: "NFL Trivia",
    description: "",
    episode_number: 23,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VfW2Ci2K5JCM/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/fW2Ci2K5JCM",
  },
  {
    id: "24",
    status: "published",
    title: "Ladies Of R&amp;B",
    description: "",
    episode_number: 24,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VHwAb80SdQ-0/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/HwAb80SdQ-0",
  },
  {
    id: "25",
    status: "published",
    title: "You Eat What?",
    description: "",
    episode_number: 25,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/Vix6La9VKSFc/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/ix6La9VKSFc",
  },
  {
    id: "26",
    status: "published",
    title: "That's s flag on the play",
    description: "",
    episode_number: 26,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VJzQ1ec6h-V4/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/JzQ1ec6h-V4",
  },
  {
    id: "27",
    status: "published",
    title: "Friday Fun!",
    description: "",
    episode_number: 27,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VLzqWEJvFeL4/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/LzqWEJvFeL4",
  },
  {
    id: "28",
    status: "published",
    title: "These guys can sing a lil too",
    description: "",
    episode_number: 28,
    date: "",
    thumbnail_url: "https://img.youtube.com/vi/VTXb40wkG_Gg/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/embed/TXb40wkG_Gg",
  },
];
